// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= How to fix NoSuchMethodError in com/sun/tools/javac/ when running unit tests
:page-layout: wikimenu
:page-tags: wik
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqTestUnitTestFailsNoSuchMethodError
:description: Apache NetBeans wiki DevFaqTestUnitTestFailsNoSuchMethodError
:toc: left
:toc-title:
:page-syntax: true
:page-aliases: ROOT:wiki/DevFaqTestUnitTestFailsNoSuchMethodError.adoc

== Problem

My unit test fails with NoSuchMethodError somewhere in com/sun/tools/javac/... but it runs OK inside NetBeans runtime.

Taken from nbdev-mailing list:

----
Hi,

I have a code that analyzes content of Java source file (generated R.java) in one of nbandroid plugin
(http://kenai.com/projects/nbandroid/sources/mercurial/content/grammars/src/org/netbeans/modules/android/grammars/ProjectRefResolver.java?rev=609). 
It worked fine and I was interested in VariableName.getSimpleName() value. 
Now I added VariableName.getConstant() and my unit test fails with NoSuchMethodError somewhere in com/sun/tools/javac/... 
but it runs OK inside NetBeans runtime.

I suspect this is because my code is compiled against NetBeans' version of 
javac but the test runs with classes from tools.jar shipped with JDK. Is this 
correct? How do I fix that (I want running code *and* running test)?

-Radim
----


== Solution

Please try to add: requires.nb.javac=true into the nbproject/project.properties of that project. 
jlahoda