// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= What is an autoload module?
:page-layout: wikidev
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki Autoload
:description: Apache NetBeans wiki Autoload
:toc: left
:toc-title:
:page-syntax: true
:page-wikidevsection: _module_system
:page-position: 10

The *autoload* in the xref:front::index.adoc[NetBeans] module system world means that certain module is turned on when _needed_. 
In contrast to regular modules which require some manual action (user locating a module and activating it) to turn them on, the *autoload* modules are opaque for users and managed solely by the infrastructure. 
As soon as there is some module needing (by dependency or require/needs token) an *autoload* module, the infrastructure enables it.

In the link:http://wiki.apidesign.org/wiki/OSGi[OSGi] mode, the meaning of *autoload* remains as close as the original meaning. 
The bundle JAR is registered to the underlaying link:http://wiki.apidesign.org/wiki/OSGi[OSGi] framework, but it is not _started_ until there is some NetBeans module which would depend on the bundle. 
If there is no such xref:front::index.adoc[NetBeans] module, the link:http://wiki.apidesign.org/wiki/OSGi[OSGi] bundle remains in _installed_ state (or _resolved_?).

The *autoload* mode is most suitable for link:http://wiki.apidesign.org/wiki/OSGi[OSGi] bundles which shall be left in the full control of the link:http://wiki.apidesign.org/wiki/OSGi[OSGi] container. 
For example there can be other link:http://wiki.apidesign.org/wiki/OSGi[OSGi] bundles which may later _start_ such bundles. 
Such enablement is outside of control of the xref:front::index.adoc[NetBeans] module system and is temporary (on subsequent launch of the system the module remains *autoload.adoc*).
