// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= What is an ExplorerManager?
:page-layout: wikidev
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqExplorerManager
:description: Apache NetBeans wiki DevFaqExplorerManager
:toc: left
:toc-title:
:page-syntax: true
:page-wikidevsection: _nodes_and_explorer
:page-position: 3
:page-aliases: ROOT:wiki/DevFaqExplorerManager.adoc

include::front::partial$database.adoc[]

You do not directly set the Node that is displayed by an xref:./DevFaqExplorerViews.adoc[Explorer view ] component (Swing components that display xref:./DevFaqWhatIsANode.adoc[Nodes ]) by calling a method on that component.  Rather, you set that kind of information by finding the _manager_ for that component - it's what is in charge of what node is displayed, selected, etc.

The manager may be explicitly set on an Explorer view, but usually this is not necessary.  When you add a view component (such as a link:{apidoclink}orgOpenideOxplorer/org/openide/explorer/view/BeanTreeView.html[BeanTreeView ]) to a Swing container, it will search backward through its parent, it's parent's parent, and so forth, looking for a component that implements link:{apidoclink}orgOpenideOxplorer/org/openide/explorer/ExplorerManager.Provider.html[ExplorerManager.Provider ] (an interface with one method - `getExplorerManager()`).  That ExplorerManager is what will determine what is displayed.

While this may seem like an unnecessary layer of indirection, it is actually quite powerful:  It makes it possible to very simply create master-detail views ala Windows Explorer:  Just add two views to a JPanel subclass that implements link:{apidoclink}orgOpenideOxplorer/org/openide/explorer/ExplorerManager.Provider.html[ExplorerManager.Provider ].  It is very easy to set it up so changing the selection in one causes the other one to show the children of the selected object - just the way selecting a folder in Windows Explorer does.

See also the link:{apidoclink}orgOpenideOxplorer/org/openide/explorer/ExplorerManager.html[ExplorerManager javadoc ].  The xref:./DevFaqCreateExplorerPanel.adoc[FAQ about showing explorer views in the main window ] includes sample usage of ExplorerManager.
