// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Some module in the IDE etc. already has a menu item I can use. I just want to rename it. Can I?
:page-layout: wikidev
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqRenamingMenuItem
:description: Apache NetBeans wiki DevFaqRenamingMenuItem
:toc: left
:toc-title:
:page-syntax: true
:page-wikidevsection: _actions_how_to_add_things_to_files_folders_menus_toolbars_and_more
:page-position: 26
:page-aliases: ROOT:wiki/DevFaqRenamingMenuItem.adoc

include::front::partial$database.adoc[]

If you are creating a custom application (e.g. *Standalone Application* in suite project properties) you specify a _branding_ for the application. You can then override localized text strings from platform modules without modifying those modules directly; the overrides will be active whenever your branding is selected (this part is taken care of for you by the suite build harness). You will need to locate the module which defines the menu item and find the localized `Bundle.properties` which gives a label for it. Then you can create a file in your suite project like

`branding/modules/''jarname''.jar/''path''/Bundle.properties`

containing definitions of overridden labels.

When you enable branding on a suite the IDE automatically brands a few bundle strings for the main window title and so on, so you can look at these files for examples.

The Branding menu item on a suite (or Maven app project) lets you search for other strings and override them easily.

See also link:{apidoclink}org-openide-modules/org/openide/modules/doc-files/i18n-branding.html[Technical details]

Applies to: NetBeans 5.0, 5.5, 6.x
