// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= What are `{asterisk}.settings` files?
:page-layout: wikidev
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqDotSettingsFiles
:description: Apache NetBeans wiki DevFaqDotSettingsFiles
:toc: left
:toc-title:
:page-syntax: true
:page-wikidevsection: _configuration_how_modules_install_things
:page-position: 8

include::front::partial$database.adoc[]

`.settings` files are similar to xref:./DevFaqInstanceDataObject.adoc[DevFaqInstanceDataObject `.instance` files],
with the difference that they are XML format, and can contain serialized data rather than just default instances.

Since the introduction of link:{apidoclink}org-openide-util/org/openide/util/NbPreferences.html[`NbPreferences`] to replace link:{apidoclink}org-openide-options/org/openide/options/SystemOption.html[SystemOption],
very little new code uses these files, and they should be considered semi-deprecated.  They are difficult and error-prone to use, and have a fair amount of overhead.  The Window System still requires them to be used to persist the state of opened windows/tabs (caret position, what file is opened, or other state that should be restored when reopening a link:{apidoclink}org-openide-windows/org/openide/windows/TopComponent.html[TopComponent] after a restart) across application runs.

A `.settings` file can encode the entire parent class and interface hierarchy of the object it represents, so that a query about _whether an object of a given type is present_ (such as using `link:{apidoclink}org-openide-util-lookup/org/openide/util/lookup/Lookups.html#forPath(java.lang.String)[Lookups.forPath](&quot;path/to/folder&quot;).allItems()`) can be answered without actually creating an instance of the object.  

Settings files are also useful if you are declaring some objects in a layer file (see xref:./DevFaqModulesLayerFile.adoc[DevFaqModulesLayerFile]) _and intend to write them back out to disk after they have been modified in-memory_ (note this involves writing ugly and inefficient hexadecimal-encoded serialized data into XML files - if the object is a singleton, using `link:{apidoclink}org-openide-util/org/openide/util/NbPreferences.html[NbPreferences]` will be both more efficient and more readable).

== Example

[source,xml,subs="verbatim,macros"]
----

<?xml version="1.0"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN"
                          "link:http://www.netbeans.org/dtds/sessionsettings-1_0.dtd[http://www.netbeans.org/dtds/sessionsettings-1_0.dtd]">
<settings version="1.0">
    <module name="org.netbeans.core.io.ui/1" spec="1.6"/>
    <instanceof class="org.openide.windows.TopComponent"/>
    <instanceof class="org.netbeans.core.io.ui.IOWindow$IOWindowImpl"/>
    <serialdata class="org.netbeans.core.io.ui.IOWindow$IOWindowImpl">
        ACED0005737200296F72672E6F70656E6964652E7...
    </serialdata>
</settings>
----
