// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Why does `TopComponent` have a `getLookup()` method? What is it for?
:page-layout: wikimenu
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki DevFaqWindowsTopComponentLookup
:description: Apache NetBeans wiki DevFaqWindowsTopComponentLookup
:toc: left
:toc-title:
:page-syntax: true
:page-wikidevsection: _window_system
:page-position: 10
:page-aliases: ROOT:wiki/DevFaqWindowsTopComponentLookup.adoc

The windowing system is what manages xref:./DevFaqTrackGlobalSelection.adoc[global selection].  In olden times, selection meant the activated xref:./DevFaqWhatIsANode.adoc[Node].

In modern NetBeans, the global selection is really whatever objects are in the focused  `xref:./DevFaqWindowsTopComponent.adoc[TopComponent]`'s xref:./DevFaqLookup.adoc[Lookup].  It so happens that most standard TopComponents display `xref:./DevFaqWhatIsANode.adoc[Node]`s - so for most `TopComponent`s, the component's `Lookup` is just proxying the `Lookup` of the selected Node.

Rather than thinking of the selection as some specific object or Node, it is more useful to think of it as a grab bag of stuff provided by whatever component happens to have focus.  If you use `xref:./DevFaqTrackGlobalSelection.adoc[Utilities.actionsGlobalContext()]`, you do not have to track all the different grab-bags of stuff provided by different components - you can get one grab bag of stuff which whose content will simply change (notifying you in the process) when focus moves to a different component.

So the `TopComponent`'s `Lookup` is a way to provide your particular grab bag of stuff - it can be the lookup of a `Node` if you want, or it can be/contain whatever else or in addition you'd like to put there.
