// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= InitializationOfDefaultLookup
:page-layout: wiki
:page-tags: wik
:jbake-status: published
:keywords: Apache NetBeans wiki InitializationOfDefaultLookup
:description: Apache NetBeans wiki InitializationOfDefaultLookup
:toc: left
:toc-title:
:page-syntax: true


Lookup is a general API for registering and querying instances of services or other objects. There are two basic uses of lookup: a particular context, e.g. a node selection passed to an action; and global default lookup, used to register services in the system.

When writing a unit test that tests code which (directly or indirectly) calls Lookup.getDefault() you should consider what the available instances will be. By default, any classes registered in META-INF/services/* resources in JARs in the test classpath will be available.

If you want to override this, the easiest thing is to use MockServices, from the nbjunit test utilities library. For example, you may want to register a special ProjectFactory for use within one test, because you want a simplified project type you can control to test some features of code which works with projects. Here is how:

[source,java]
----
protected void setUp() throws Exception {
    super.setUp();
    MockServices.setServices(TestingProjectFactory.class);
}
public static class TestingProjectFactory implements ProjectFactory {
    // implement interface methods...
}
----

Now e.g. ProjectManager.getDefault().findProject(...) should give TestingProjectFactory a chance to recognize the project.

Note that TestingProjectFactory will be available in default lookup as the first ProjectFactory instance, but any others registered in META-INF/services/* will still be available "later". (Lookup is ordered.) Many services placed in lookup (e.g. DialogDisplayer) are intended to be singletons, in which case installing an instance using MockServices effectively means you can override the default implementation.

You can also add and remove services while the test runs. Every call to setServices overrides the previous call.

Code which directly looks in META-INF/services/* - for example, calls to java.util.Service, as well as many subsystems such as JAXP - should also see services registered this way.

If you wish to register individual instances to default lookup, without the requirement that they be default instances of public classes, you can also use MockLookup. See xref:./UsefulTestClassesInModules.adoc[UsefulTestClassesInModules]. 
