// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Netbeans Rcp Antlr Format And Indent
:page-layout: wikimenu
:page-tags: wiki, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki Netbeans Rcp Antlr Format And Indent
:description: Apache NetBeans wiki Netbeans Rcp Antlr Format And Indent
:toc: left
:toc-title:
:page-syntax: true
include::front::partial$database.adoc[]

I do not have the formatting and indenting fully working yet, but I did figure out the integration points. 
It took me almost a full day to figure out how to just get that working so I figure it was worth at least starting a tutorial.

It is actually quite simple! 
And, once you have things registered correctly, the next step (to be documented later) will be to use your ANTLR Lexer to do the formatting.

This is part of the xref:./Netbeans_Rcp_Antlr_Integration_Index.adoc[ANTLR integration tutorials].

== IndentTask

=== 1. 

The indent task will make a callback to the reindent() method when the enter key is pressed while editing. The Context object contains everything that you will need, including the editor document object. It should just be a matter of taking the text after the cursor and before the next line and indenting things properly.

[source,java]
----
public class SqlIndentTask implements IndentTask {
    
    private Context context;

    SqlIndentTask(Context context) {
        this.context = context;
    }

    public void reindent() throws BadLocationException {
        System.out.println("we will indent this now");
    }

    public ExtraLock indentLock() {
        return null;
    }

}
----

=== 2. 

The IndentTask.Factory is the hook for Netbeans to use your IndentTask.

[source,java]
----
public class SqlIndentTaskFactory implements IndentTask.Factory {

    public IndentTask createTask(Context context) {
        return new SqlIndentTask(context);
    }

}
----

=== 3. 

Lastly, register the IndentTask with the layer.xml file.

[source,xml]
----
<folder name="Editors">
    <folder name="text">
        <folder name="x-sqlr">
            <file name="com-sqlraider-editor-format-SqlIndentTaskFactory.instance"/>
        </folder>
    </folder>
</folder>
----

== ReformatTask

=== 1. 

The reformat task will make a callback to the reformat() method when you invoke the built in Netbeans format command. In other words when you use the menu Source -> Format action or press Alt+Shift+F. The Context object contains everything that you will need, including the editor document object. It should just be a matter of taking the text and running it through the ANTLR Lexer to format things properly.

[source,java]
----
public class SqlReformatTask implements ReformatTask {

    private Context context;

    public SqlReformatTask(Context context) {
        this.context = context;
    }

    @Override
    public void reformat()
            throws BadLocationException {
        System.out.println("we will format this now");
    }

    @Override
    public ExtraLock reformatLock() {
        return null;
    }

}
----

=== 2. 

The ReformatTask.Factory is the hook for Netbeans to use your ReformatTask.

[source,java]
----
public class SqlReformatTaskFactory implements ReformatTask.Factory {

    public ReformatTask createTask(Context context) {
        return new SqlReformatTask(context);
    }
}
----

=== 3. 

Lastly, register the ReformatTask with the layer.xml file.

[source,xml]
----
<folder name="Editors">
    <folder name="text">
        <folder name="x-sqlr">
            <file name="com-sqlraider-editor-format-SqlReformatTaskFactory.instance"/>
        </folder>
    </folder>
</folder>
----

