// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Overview
:page-layout: wikimenu
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki JavaHT Overview
:description: Apache NetBeans wiki JavaHT Overview
:toc: left
:toc-title:
:page-syntax: true
:page-aliases: ROOT:wiki/JavaHT_Overview.adoc

When working with the Java related APIs in the NetBeans IDE we recommend making yourself familiar with some of the basic concepts which are used. The APIs are based directly on the APIs of the javac compiler. Some of the APIs are taken directly from javac. Some are added in order to integrate javac into the IDE properly and in order to supply functionality not provided by javac (e.g. modifying code). Being able to understand the basic of how javac works also helps.

Please note that there are some pitfalls when using these APIs. Make sure you know what these are and how to detect basic mistakes (both described later in the text) in order to not harm the performance of the IDE.

The essential packages a module writer will be interested in are:

* javax.lang.model.element, javax.lang.model.type, javax.lang.model.util. - For reading high level java language elements (classes, methods, fields, ...) and for working with types. These are the same APIs as those used for writing annotation processors (AKA JSR269).
* com.sun.source.tree, com.sun.source.util - For reading the syntactic structure of a java source i.e. AST (Abstract Syntax Trees)
* org.netbeans.java.source, org.netbeans.java.source.support - For integration with the IDE, additional utility methods and doing source code modifications. 