// 
//     Licensed to the Apache Software Foundation (ASF) under one
//     or more contributor license agreements.  See the NOTICE file
//     distributed with this work for additional information
//     regarding copyright ownership.  The ASF licenses this file
//     to you under the Apache License, Version 2.0 (the
//     "License"); you may not use this file except in compliance
//     with the License.  You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//     Unless required by applicable law or agreed to in writing,
//     software distributed under the License is distributed on an
//     "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//     KIND, either express or implied.  See the License for the
//     specific language governing permissions and limitations
//     under the License.
//

= Source Files vs. Class Files
:page-layout: wikimenu
:page-tags: wiki, devfaq, needsreview
:jbake-status: published
:keywords: Apache NetBeans wiki JavaHT SourceFilesVsClassFiles
:description: Apache NetBeans wiki JavaHT SourceFilesVsClassFiles
:toc: left
:toc-title:
:page-syntax: true
:page-aliases: ROOT:wiki/JavaHT_SourceFilesVsClassFiles.adoc

Parsing a file from the source code is time and memory consuming task, compared to simple loading of a class file. 
So, it is important for all the authors of a code in the IDE to know if their code requires parsing a source file or if it is sufficient to use data from a class file.

Another significant difference between these two approaches is that the Trees are available only if the file has been compiled from the source file. 
The Elements load from a class file are supposed to be "identical" to elements got by parsing the corresponding source file.

The rule of thumb here is that if you need only classes, their methods, constructors, fields and inner classes and their annotations, loading the data from the class file is sufficient for you. 
If you need access of the method content (statements), etc., you need to get data by parsing the source code. 